"use client";
import {useEffect,useState} from 'react';
type Item={title:string;url:string;publishedAt:string};
type Source={id:string;name:string;home:string;articles:Item[];error:string|null;checkedAt:string};
const defaults:Source[]=[{id:'nikkei',name:'日本経済新聞',home:'https://www.nikkei.com',articles:[],error:null,checkedAt:''},{id:'quick',name:'QUICK',home:'https://moneyworld.jp',articles:[],error:null,checkedAt:''}];
const date=(v:string)=>new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(v));
export default function Home(){const [sources,setSources]=useState(defaults),[busy,setBusy]=useState(true),[error,setError]=useState(false);
async function refresh(){setBusy(true);try{const r=await fetch('/api/news',{cache:'no-store'});if(!r.ok)throw Error();setSources(((await r.json()) as {sources:Source[]}).sources);setError(false);}catch{setError(true);}finally{setBusy(false);}}
useEffect(()=>{void refresh();const t=setInterval(refresh,300000);return()=>clearInterval(t);},[]);
return <main><header><a className="brand" href="/">経済ニュース<span>DAILY BRIEF</span></a><span className="edition">日本語版 / JST</span></header><section className="intro"><div><p className="eyebrow">NIKKEI & QUICK</p><h1>いま、押さえたいニュース。</h1><p className="description">日経・QUICKの最新記事を、それぞれ3件。</p></div><button disabled={busy} onClick={refresh}>{busy?'更新中…':'ニュースを更新 ↻'}</button></section><div className="status"><span>5分ごとに自動更新</span><span>{sources[0].checkedAt?`取得確認：${date(sources[0].checkedAt)}`:'ニュースを取得しています'}</span></div>{error&&<p role="alert">更新できませんでした。時間をおいて再度お試しください。</p>}<div className="columns">{sources.map(s=><section key={s.id} className={'source '+s.id}><div className="source-heading"><div><p className="eyebrow">{s.id==='nikkei'?'NIKKEI':'QUICK MONEY WORLD'}</p><h2>{s.name}</h2></div><span className="count">03<small>最新記事</small></span></div>{s.error?<div className="empty"><h3>ニュースを取得できませんでした</h3><p>次回の自動更新をお待ちいただくか、公式サイトをご覧ください。</p></div>:s.articles.length?s.articles.map((a,i)=><article key={a.url}><span className="number">0{i+1}</span><div><time dateTime={a.publishedAt}>{date(a.publishedAt)}</time><h3><a href={a.url} target="_blank" rel="noopener noreferrer">{a.title} <span className="arrow">↗</span></a></h3></div></article>):<div className="empty">{busy?'ニュースを読み込んでいます…':'現在表示できる記事がありません。'}</div>}<a className="source-link" href={s.home} target="_blank" rel="noopener noreferrer">公式サイトへ <span>↗</span></a></section>)}</div><footer><p>Google ニュース掲載記事を公開日時順に表示。公式の重要度ランキングではありません。</p><p>見出しの配信には遅れが生じる場合があります。記事の全文は配信元でご確認ください。</p></footer></main>}
